"""Derives the character tables in _tables.py from Unicode's data and latex2mathml's unicode-math
symbol list -- the rules live here, the tables are generated so importing them costs nothing
(building them at import took ~5 ms, paid by every CLI call). After a Python (Unicode) or
latex2mathml upgrade, regenerate: `python -m mathunicode._build_tables`; tests/test_tables.py
fails until then."""

import re
import unicodedata
from importlib.metadata import version
from importlib.resources import files
from pathlib import Path


def sub_sup() -> tuple[dict[str, str], dict[str, str]]:
    """Unicode's sub/superscript forms, from its <sub>/<super> decompositions: script and modifier
    letters below Latin Extended-D (U+A700), whose recent additions (ꟲ for C) fonts often lack."""
    sub: dict[str, str] = {}
    sup: dict[str, str] = {}
    for c in map(chr, range(0xA700)):
        d = unicodedata.decomposition(c).split()
        if len(d) == 2 and d[0] in ("<sub>", "<super>") and re.search(r"SCRIPT|MODIFIER", unicodedata.name(c, "")):
            (sub if d[0] == "<sub>" else sup).setdefault(chr(int(d[1], 16)), c)
    sub["-"], sup["-"] = sub["−"], sup["−"]
    sup.update({"∘": "°"} | {c: c for c in "′″‴°*"})  # a raised ring is a degree; these are already raised
    return sub, sup


def classes() -> dict[str, str]:
    """TeX's atom class of each symbol that isn't Ord, from unicode-math's symbol list -- plain TeX's
    own mathcodes for the three ASCII characters where they differ ('/' Ord, ':' Rel, '!' Close)."""
    tex = {"B": "Bin", "V": "Bin", "R": "Rel", "L": "Op", "O": "Open", "C": "Close", "P": "Punct", "F": "Fence"}
    out = {"/": "Ord", ":": "Rel", "!": "Close"}
    for line in (files("latex2mathml") / "unimathsymbols.txt").read_text(encoding="utf-8").splitlines():
        f = line.split("^")
        if len(f) > 4 and len(f[1]) == 1 and not line.startswith("#"):
            out.setdefault(f[1], tex.get(f[4], "Ord"))
    return {c: k for c, k in out.items() if k != "Ord" or c == "/"}


def styled() -> dict[str, tuple[str, str]]:
    """Unicode's styled letters by style name ('BOLD ITALIC', 'DOUBLE-STRUCK'): (base letters, their
    styled forms), from the Mathematical Alphanumeric and Letterlike Symbols blocks."""
    out: dict[str, tuple[str, str]] = {}
    for c in map(chr, [*range(0x1D400, 0x1D800), *range(0x2100, 0x2150)]):
        m = re.match(r"(?:MATHEMATICAL )?(.+?) (?:CAPITAL|SMALL|DIGIT)\b", unicodedata.name(c, ""))
        base = unicodedata.normalize("NFKC", c)
        if m and len(base) == 1:
            bases, forms = out.get(m[1].replace("BLACK-LETTER", "FRAKTUR"), ("", ""))
            if base not in bases:
                out[m[1].replace("BLACK-LETTER", "FRAKTUR")] = (bases + base, forms + c)
    return out


def _string(text: str, indent: str) -> str:
    """A long string literal, wrapped to fit the line length."""
    return "(\n" + "".join(f"{indent}    {text[i:i + 60]!r}\n" for i in range(0, len(text), 60)) + f"{indent})"


def source() -> str:
    sub, sup = sub_sup()
    by_class: dict[str, str] = {}
    for c, k in classes().items():
        by_class[k] = by_class.get(k, "") + c
    lines = [
        '"""Generated by `python -m mathunicode._build_tables` from Unicode and unicode-math data: don\'t edit."""',
        "",
        f"UNICODE_VERSION = {unicodedata.unidata_version!r}",
        f"LATEX2MATHML_VERSION = {version('latex2mathml')!r}",
        "",
        f"SUB = dict(zip({_string(''.join(sub), '')}, {_string(''.join(sub.values()), '')}, strict=True))",
        f"SUP = dict(zip({_string(''.join(sup), '')}, {_string(''.join(sup.values()), '')}, strict=True))",
        "",
        "# TeX's atom class of each symbol that isn't Ord",
        "CLASS = {c: k for k, chars in {",
        *(f"    {k!r}: {_string(chars, '    ')}," for k, chars in by_class.items()),
        "}.items() for c in chars}",
        "",
        "# Styled letters: (style words, base letter) -> styled letter",
        "STYLED = {(frozenset(style.replace('-', ' ').split()), b): s for style, (bases, forms) in {",
        *(f"    {style!r}: ({_string(b, '    ')}, {_string(s, '    ')})," for style, (b, s) in styled().items()),
        "}.items() for b, s in zip(bases, forms, strict=True)}",
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    Path(__file__).with_name("_tables.py").write_text(source(), encoding="utf-8")
